# Import lib

In [66]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold

# Bước 1: Đọc file Wine.csv

In [21]:
data = pd.read_csv('/content/drive/MyDrive/Học tập/CS116_LapTrinhPython/LogisticRegression_with_PCA/Wine.csv')

In [22]:
data

Alcohol  Malic_Acid   Ash  ...  OD280  Proline  Customer_Segment
0      14.23        1.71  2.43  ...   3.92     1065                 1
1      13.20        1.78  2.14  ...   3.40     1050                 1
2      13.16        2.36  2.67  ...   3.17     1185                 1
3      14.37        1.95  2.50  ...   3.45     1480                 1
4      13.24        2.59  2.87  ...   2.93      735                 1
..       ...         ...   ...  ...    ...      ...               ...
173    13.71        5.65  2.45  ...   1.74      740                 3
174    13.40        3.91  2.48  ...   1.56      750                 3
175    13.27        4.28  2.26  ...   1.56      835                 3
176    13.17        2.59  2.37  ...   1.62      840                 3
177    14.13        4.10  2.74  ...   1.60      560                 3

[178 rows x 14 columns]

In [82]:
X = data.drop(columns=['Customer_Segment'])
y = data['Customer_Segment']

In [83]:
X

Alcohol  Malic_Acid   Ash  ...   Hue  OD280  Proline
0      14.23        1.71  2.43  ...  1.04   3.92     1065
1      13.20        1.78  2.14  ...  1.05   3.40     1050
2      13.16        2.36  2.67  ...  1.03   3.17     1185
3      14.37        1.95  2.50  ...  0.86   3.45     1480
4      13.24        2.59  2.87  ...  1.04   2.93      735
..       ...         ...   ...  ...   ...    ...      ...
173    13.71        5.65  2.45  ...  0.64   1.74      740
174    13.40        3.91  2.48  ...  0.70   1.56      750
175    13.27        4.28  2.26  ...  0.59   1.56      835
176    13.17        2.59  2.37  ...  0.60   1.62      840
177    14.13        4.10  2.74  ...  0.61   1.60      560

[178 rows x 13 columns]

In [84]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Customer_Segment, Length: 178, dtype: int64

# Bước 2: Chuẩn hóa đặc trưng đầu vào X bằng Standard Scaler

In [15]:
scaler = StandardScaler()

In [31]:
X = scaler.fit_transform(X)

In [33]:
X.shape

(178, 13)

In [85]:
y = np.array(y)
y.shape

(178,)

In [35]:
X

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [46]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3])

# Bước 3: PCA để nén đặc trưng đầu vào từ 13 chiều xuống còn 2 chiều

In [38]:
pca = PCA(n_components=2)

In [40]:
X = pca.fit_transform(X)

In [42]:
X.shape

(178, 2)

In [ ]:
X

# Bước 4: Chia tập dữ liệu thành 2 phần train test với tỉ lệ 8/2

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [48]:
X_train.shape

(142, 2)

In [49]:
X_test.shape

(36, 2)

In [50]:
y_train.shape

(142,)

In [51]:
y_test.shape

(36,)

# Bước 5: Dùng logistic Regression để phân lớp dữ liệu

In [54]:
model = LogisticRegression(random_state=0)

In [55]:
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [56]:
y_predict = model.predict(X_test)

In [57]:
y_predict.shape

(36,)

In [58]:
y_predict

array([1, 1, 3, 1, 2, 1, 2, 3, 2, 3, 1, 3, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 3, 3, 3, 2, 2, 2, 1, 1, 2, 3, 1, 1, 1])

In [59]:
y_test

array([1, 1, 3, 1, 2, 1, 2, 3, 2, 3, 1, 3, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 3, 3, 3, 2, 2, 2, 1, 1, 2, 3, 1, 1, 1])

# Bước 6: Đánh giá mô hình với độ đo accuracy

In [64]:
print(classification_report(y_test,y_predict))
print('Accuracy Score: ',accuracy_score(y_test,y_predict))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        14
           3       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

Accuracy Score:  1.0


# Bước 7: Đánh giá mô hình bằng cross validation với K=5

In [72]:
kf = KFold(n_splits=5, shuffle=True)

In [77]:
accuracy_list = []
for train_index, test_index in kf.split(X, y):
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = y[train_index], y[test_index]

  model.fit(X_train, y_train)
  y_predict = model.predict(X_test)
  accuracy_list.append(accuracy_score(y_test,y_predict))

In [78]:
accuracy_list

[0.9722222222222222,
 0.9444444444444444,
 0.9722222222222222,
 0.9428571428571428,
 0.9714285714285714]

In [79]:
np.mean(accuracy_list)

0.9606349206349206